### ISSUE TITLE
[Task] - Persist RQA

### ISSUE THREAD

**Issue by levinkerschberger** [dqualizer/dqAnalyzer-react#17]
## Goal
A storage will keep data out of our code.

## Description
We are working with multiple types of data now.
- Domain-Architecture-Mappings
- Loadtest-Specification-Parameters
- Runtime Quality Analysis Definitions
- Domain-Storys

For all these, dqedit takes care of storing the data. dqanalyzer is just responsible for RQAs. Could be stored in same DB.

MongoDB, Relational Database, something else?
Choose a storage and document the reasons for the decision.

## User Story

- [ ] user-story #16 
- [ ] user-story #13

**Comment by julianbrott** [comment]
@levinkerschberger according to our documentation the task is done, should this ticket be closed?
