### ISSUE TITLE
[Feature] - Defining complex RQA Definitions

### ISSUE THREAD

**Issue by levinkerschberger** [dqualizer/dqAnalyzer-react#26]
## Is your feature request related to a problem? Please describe.

Currently, you can only perform a (single) load test with the dqualizer.
Later it should be possible to create an RQA definition, which includes monitoring requests, chaos experiments, load tests, and more. In particular, an RQA should also have different kinds of stimuli and responses that can be defined on multiple domain elements. For this purpose, an RQA definition will be created in the dqAnalyzer. 

_Currently, the RQA definition object is created in the load test menu.
This is too late and not correct. ( -> this statement needs further explanation)_

## Describe the solution you'd like

We need to provide the functionality to store, retrieve, manage, and create new RQAs and further split up the RQA into more independent and scalable stimuli/response parts. 
When a load test is created, it should only be added to the currently selected RQA instead of creating a completely new object each time.

## Describe alternatives you've considered

I suggest working directly with a database. A user model does not have to exist yet. Later, however, it could be the case that users also only have access to their RQA definitions, etc.
Therefore I would suggest to create a storage for RQA definitions.

**Comment by franksn90** [comment]
Refined and now splitted into:
#38 
#39 
#40 
#41
