### ISSUE TITLE
[User-Story] - Selection of a Domain

### ISSUE THREAD

**Issue by levinkerschberger** [dqualizer/dqAnalyzer-react#7]
## Story

As a Domain-Expert, I want to select the domain, which I want analyze so I can work in multiple domains.

## Acceptance Criteria

- [ ] The user can choose between different domains
- [ ] The selection is integratable into a identity and access management concept (IAM)

Both of those criterias are issued in this task: #18

**Comment by julianbrott** [comment]
@levinkerschberger according to our documentation the task is done, should this be closed?
