### ISSUE TITLE
[Task] - Create Demo Application

### ISSUE THREAD

**Issue by levinkerschberger** [dqualizer/dqAnalyzer-react#9]
## Goal
We have a Demo-Application, which can be modeled with the domain-architecture-mapping schema, to use it for development and showcases.

## Description
I´d suggest to build the "Kino-Kasse" Domain in Spring Boot.
Requirements are:
- [ ] Rest-based
- [ ] Multiple services, with communication between them
- [ ] Multiple user-groups, which can do different things
- [ ] Endpoints, which represent a workflow / domain-story

## User Story

- [ ] #6 

## Dependencies
- [ ] Blocked by...
Create Repositories for the Demo-Services and link them here

**Comment by franksn90** [comment]
Not sure whether this is necessary - it seems to be a lot of effort. Why not use an existing system?
